# Generated by Django 4.0.4 on 2022-05-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('public', models.BooleanField(default=False)),
                ('answer', models.TextField(blank=True, null=True)),
                ('createdAnswer', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Здоровье', 'Здоровье'), ('Обучение', 'Обучение'), ('Финансы', 'Финансы'), ('Документы', 'Документы'), ('Другое', 'Другое')], max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
