# Generated by Django 4.0.4 on 2022-05-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_question_name_question_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='createdAnswer',
            new_name='created_answer',
        ),
    ]
